apiVersion: v1
kind: Service
metadata:
  name: ordersspring
  labels:
    helm.sh/chart: quickstart-java-service-0.2.0
    app.kubernetes.io/name: ordersspring
    app.kubernetes.io/instance: ordersspring
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    konveyor.io/business-service: "Retail"
    konveyor.io/archetype: "Spring Boot"
  annotations:
    konveyor.io/source-repository: https://github.com/rromannissen/rhoar-microservices-demo.git
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ordersspring
    app.kubernetes.io/instance: ordersspring
